# params.yaml
data_ingestion:
  test_size: 0.25

feature_engineering:
  max_features: 10
  create_interaction: True

model_building:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42
  class_weight: 'balanced'
  n_jobs: -1